//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lab_03.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActivityTypes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ActivityTypes()
        {
            this.SubscriptionActivityTypes = new HashSet<SubscriptionActivityTypes>();
            this.TrainerActivities = new HashSet<TrainerActivities>();
        }
    
        public int activity_type_id { get; set; }
        public string activity_name { get; set; }
        public string activity_description { get; set; }
        public Nullable<decimal> activity_price { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SubscriptionActivityTypes> SubscriptionActivityTypes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TrainerActivities> TrainerActivities { get; set; }
    }
}
