//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lab_03.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class sportComplexEntities : DbContext
    {
        public sportComplexEntities()
            : base("name=sportComplexEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ActivityTypes> ActivityTypes { get; set; }
        public virtual DbSet<Cities> Cities { get; set; }
        public virtual DbSet<Clients> Clients { get; set; }
        public virtual DbSet<Gyms> Gyms { get; set; }
        public virtual DbSet<PaymentMethods> PaymentMethods { get; set; }
        public virtual DbSet<Purchases> Purchases { get; set; }
        public virtual DbSet<SportComplexes> SportComplexes { get; set; }
        public virtual DbSet<SubscriptionActivityTypes> SubscriptionActivityTypes { get; set; }
        public virtual DbSet<Subscriptions> Subscriptions { get; set; }
        public virtual DbSet<SubscriptionTerms> SubscriptionTerms { get; set; }
        public virtual DbSet<SubscriptionVisitTimes> SubscriptionVisitTimes { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TrainerActivities> TrainerActivities { get; set; }
        public virtual DbSet<Trainers> Trainers { get; set; }
        public virtual DbSet<Trainings> Trainings { get; set; }
    }
}
