//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lab_03.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubscriptionActivityTypes
    {
        public int subscription_activity_type_id { get; set; }
        public int subscription_id { get; set; }
        public int activity_type_id { get; set; }
        public Nullable<int> activity_type_amount { get; set; }
    
        public virtual ActivityTypes ActivityTypes { get; set; }
        public virtual Subscriptions Subscriptions { get; set; }
    }
}
