//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lab_03.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Subscriptions
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Subscriptions()
        {
            this.Purchases = new HashSet<Purchases>();
            this.SubscriptionActivityTypes = new HashSet<SubscriptionActivityTypes>();
        }
    
        public int subscription_id { get; set; }
        public int subscription_term_id { get; set; }
        public int subscription_vissit_time_id { get; set; }
        public Nullable<decimal> subscription_total_cost { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Purchases> Purchases { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SubscriptionActivityTypes> SubscriptionActivityTypes { get; set; }
        public virtual SubscriptionTerms SubscriptionTerms { get; set; }
        public virtual SubscriptionVisitTimes SubscriptionVisitTimes { get; set; }
    }
}
