//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lab_03.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Trainings
    {
        public int training_id { get; set; }
        public System.DateTime training_start_date_time { get; set; }
        public Nullable<System.DateTime> training_end_date_time { get; set; }
        public int trainer_id { get; set; }
        public int gym_id { get; set; }
    
        public virtual Gyms Gyms { get; set; }
        public virtual Trainers Trainers { get; set; }
    }
}
